name: Deploy to EC2

on:
  push:
    branches:
      - clouds-lab2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.21.255.185 >> ~/.ssh/known_hosts
          rsync -avz --exclude '.git*' ./ ec2-user@51.21.255.185:/home/ec2-user/backend/

          ssh ec2-user@51.21.255.185 << 'EOF'
            cd /home/ec2-user/backend
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_NAME=${{ secrets.DB_NAME }}
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f "python3 application.py" || true
            nohup python3 application.py > app.log 2>&1 &
          EOF
