name: Build and Deploy to ECS

on:
  push:
    branches: [ clouds-lab2 ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login \
            --username AWS \
            --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Docker image
        run: |
          docker build -t backend .

      - name: Tag image
        run: |
          docker tag backend:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster lpnu-clouds-cluster \
            --service lpnu-clouds-cluster \
            --force-new-deployment
